env:
    MANIFEST: https://github.com/Evolution-X/manifest.git -b udc --depth=1
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/ij-israfil/local_manifest.git -b evox-a14
    TARGET: evolution 
    LUNCH_COMBO: evolution_${DEVICE}-userdebug
    OUTPUT: e*.zip
    CLO: Drive3:Evox
    CLO_1: ENCRYPTED[!584b549b7e1c7497c082e4d6e651f4b0008588b42560261fb5f9403d605095512d3ca0791166992f4a3bc13a3a71cd38!]
    URI: ENCRYPTED[!484fc286d14503a186ac824235ae8bd659eeb5f53194b289a8b47f607012a050d9b371b4b97806b02f5c449be903e0d0!]
    ROM_U: 0
    
task:
  name: "build"
  timeout_in: 120m
  container:
      #image: apon77/aosp:cirrus
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
