#!/bin/bash
cd ~/$CIRRUS_WORKING_DIR
export CCACHE_DIR=/$CIRRUS_WORKING_DIR/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 100G
ccache -o compression=true
ccache -z
. build/envsetup.sh
lunch "$LUNCH_COMBO"
m $TARGET -j8

