#!/usr/bin/env bash
set -e
cd ~/roms/$rom_name
export CCACHE_DIR=~/ccache/$rom_name/$device
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 100G
ccache -o compression=true
ccache -z
. build/envsetup.sh
lunch "$LUNCH_COMBO"
m $TARGET -j8

