#!/bin/bash
sync() {
mkdir -p ~/$CIRRUS_WORKING_DIR
cd ~/$CIRRUS_WORKING_DIR
repo init --depth=1 -u $MANIFEST
git clone $LOCAL_MANIFEST .repo/local_manifests
repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle -j8
}

echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
